---
name: Optimize Indicator params

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'optimize-indi'

jobs:
  Process:
    outputs:
      sets-list: ${{ steps.get-sets.outputs.sets }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:
        env:
          SETS_DIR: sets/optimize/indicator
        id: get-sets
        run: |
          import glob, json, os
          os.chdir(os.getenv('SETS_DIR'))
          files = glob.glob("*.set")
          print("::set-output name=sets::{}".format(json.dumps(files)))
        shell: python
      - run: echo ${{ steps.get-sets.outputs.sets }}
  Test:
    needs: Process
    runs-on: ubuntu-latest
    strategy:
      matrix:
        setfile: ${{ fromJson(needs.Process.outputs.sets-list) }}
        tf: [M1, M5]
    steps:
      - run: echo ${{ matrix.setfile }}
